### ISSUE TITLE
Fundamental understanding

### ISSUE THREAD

**Issue by shizy818** [kserve/modelmesh#19]
Hi @njhill, I'm trying understand the basic idea about model mesh. Based on document https://kserve.github.io/website/0.7/modelserving/mms/modelmesh/overview/#overview, it looks like model A is only loaded in pod 1 of Runtime X Deployment. I assume it may fails to load it in pod 2 for some reason, for example memory shortage. Then when an inference request comes in and happens to forward to pod 2, what's happening here? Would mesh component know that the model is loaded in pod 1 and forward the request?

Thank you very much!

**Comment by njhill** [comment]
@shizy818 yes, the requests are routed to loaded models regardless of which pod they enter. Also, a given model doesn't necessarily get loaded in all pods and this is intentional.
