### ISSUE TITLE
missing com.ibm.watson.modelmesh.api package?

### ISSUE THREAD

**Issue by wzhanw** [kserve/modelmesh#4]
Hi guys, 
I cloned the code and loaded the project in ide, I found some compile errors, it seems we miss the api package. 
Where to get them? Thanks.
```
import com.ibm.watson.modelmesh.api.ModelInfo;
import com.ibm.watson.modelmesh.api.ModelStatusInfo;
import com.ibm.watson.modelmesh.api.ModelStatusInfo.ModelStatus;
import com.ibm.watson.modelmesh.api.SetVModelRequest;
import com.ibm.watson.modelmesh.api.VModelStatusInfo;
import com.ibm.watson.modelmesh.api.VModelStatusInfo.VModelStatus;
```

**Comment by pugangxa** [comment]
Thanks @wzhanw These packages should be generated by protoc. But I do think these should be included in the repo.

**Comment by wzhanw** [comment]
@pugangxa you are right, after I configured the maven plugin correctly, now those missing sources were generated by the maven plugin.  Should we commit these generated codes to the repo?

**Comment by pugangxa** [comment]
Yes, I think we should commit them like go generated files. Also we need update readme to document the steps of regenerate once the proto file changed. @animeshsingh Can we have a development.md for that purpose?

**Comment by njhill** [comment]
Hey @wzhanw, @pugangxa, I think it's best to **not** include the generated files in the repo since it's done automatically as part of the build. Just like you would not commit `.class` files. It's straightforward to generate them for development purposes by just running `mvn generate-sources`.

**Comment by pugangxa** [comment]
Just thought it's similar to the pb.go files which is also committed by convention. Yes we know it can be generated but can we document somewhere to avoid this kind of issue for new guys?
