### ISSUE TITLE
rewrite modelmesh from java to golang

### ISSUE THREAD

**Issue by fsatka** [kserve/modelmesh#56]
thank you for this project!

do you have plan to rewrite modelmesh from java to golang in future? Its seems more consistent with modelmesh-serving general logic. And its seems to me will be more easly for contributing to all project.

best regards.

**Comment by njhill** [comment]
@fsatka the reason for model-mesh being in java is mostly historical, but it is heavily optimized from a performance pov for low latency and resource overhead on the inferencing path. It's not clear that this could be done as well in go (but go is great for control plane components). If it were to be rewritten then something like rust would be more interesting to look at in my opinion.
