### ISSUE TITLE
Document design decisions for decentralized scaling and share performance evaluation

### ISSUE THREAD

**Issue by Jack47** [kserve/modelmesh#94]
Hi guys modelmesh is great, especially I known IBM FASS OpenWhisk.
I'm wandering the reasons why you guys designed decentralized scale decisions?

1. do you guys have tested the performance benefits?
2. more thoughts behind this design would be appreciated~

**Comment by ckadner** [comment]
We may need to pull together some docs from various places. There is a PDF and some wiki pages and conference presentations on performance evaluations and the https://github.com/kserve/modelmesh-performance repo
